version: '3.8'
services:
    portal:
        build: ./ubuntu/
        container_name: web
        restart: always
        ports:
            - "80:80"
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
            - PHP_IDE_CONFIG= "serverName=Docker"
        volumes:
            - /Users/ec/Desktop/investprojects:/var/www/html
